services:
  webserver:
    build:
      context: .
    image: projeto
    container_name: "app"
    restart: "always"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - .:/home/node/app
    ports:
      - "5000:5000"
    environment:
      - MYSQL_PASS=<pass>
    networks:
      - app-web-net

  mysql:
    image: mysql:latest
    container_name: "mysql"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=<pass>
    networks:
      - app-web-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - /sessions
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - app-web-net

networks:
  app-web-net:
